baseURL = 'https://conecta-saber-digital.duckdns.org/'
languageCode = 'pt-br'
title = 'Conecta Saber Digital'
theme = 'book'

cleanDestinationDir = true

[markup.goldmark.renderer]
  unsafe = true

[params]

  author = "Equipe Conecta Saber Digital"
  description = "Plataforma de Alfabetização Digital e Cibersegurança"

  BookTheme = 'dark'
  BookLogo = '/img/logo.png'
